services:
  - type: web
    name: solmegle
    env: node
    buildCommand: ./build.sh
    startCommand: chmod +x ./render_start.sh && ./render_start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false # Add this manually in the dashboard
      - key: REDIS_URL
        sync: false # Add this manually in the dashboard
      - key: CORS_ORIGIN
        fromService:
          name: solmegle
          type: web
          property: url 