services:
  - type: web
    name: solmegle
    env: node
    region: ohio
    plan: free
    buildCommand: npm run render-build
    startCommand: node server/dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false # Add this manually in the dashboard
      - key: REDIS_URL
        sync: false # Add this manually in the dashboard
      - key: CORS_ORIGIN
        fromService:
          name: solmegle
          type: web
          property: url 