services:
  - type: web
    name: solmegle
    plan: free
    runtime: node
    buildCommand: |
      node verify-deployment.js
      sh ./render-build.sh
    startCommand: cd server-static && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080 